[package]
name = "ReO"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
ring = "0.16.20"
serde = "1.0"
serde_json = "1.0"
untrusted = "0.7"
hex = "0.4"
